### ISSUE TITLE
[feat] #8 singupForm

### ISSUE THREAD

**Issue by JJJiL0ng** [Leets-Official/Z-FE#8]
## 1. 무엇을?
회원정보입력 창 api 연결 및 수정
<br>

## 2. 상세 설명
회원 정보 입력후 fetch로 서버에 전달 / 중복확인 api 연동 / 가입하기 api연동
<br>

## 3. 추가 사항
x

**Comment by One-HyeWon** [comment]
이슈 번호와 작업 내용에서는 [] 는 제거하여 주세요!
